### ISSUE TITLE
bug: Capacitor 4 no work

### ISSUE THREAD

**Issue by josexs** [capawesome-team/capacitor-app-update#50]
**Plugin version:**
Last version

**Platform(s):**
Any

Hello,

I have been testing the plugin and it seems not to work correctly with capacitor 4, the app closes directly

`E/AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
    Process: com.josexs.ct, PID: 6505
    java.lang.IllegalArgumentException: com.josexs.ct: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
E/cr_VariationsSeedLoader: Failed loading variations seed. Variations disabled.`

a greeting

**Comment by josexs** [comment]
good morning

I have installed the following version following an example that you have in your repository, in Capacitor 4, and it works perfectly

"@robingenz/capacitor-app-update": "1.3.1-dev.aa49eab.1659603574"

a greeting

**Comment by robingenz** [comment]
Please have a look at the CHANGELOG.md file. 
`@robingenz/capacitor-app-update` is now deprecated. You have to install `@capawesome/capacitor-app-update` for Capacitor 4 support.
